package com.cryptosafe.app

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.cryptosafe.app.data.AppDatabase
import com.cryptosafe.app.data.Box
import com.cryptosafe.app.data.Message
import net.zetetic.database.sqlcipher.SupportOpenHelperFactory
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * اختبارات قاعدة البيانات المشفرة (SQLCipher) — تعمل على محاكي/جهاز حقيقي فقط:
 * ./gradlew connectedAndroidTest
 */
@RunWith(AndroidJUnit4::class)
class DatabaseTest {

    private lateinit var database: AppDatabase

    @Before
    fun setUp() {
        System.loadLibrary("sqlcipher")
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .openHelperFactory(SupportOpenHelperFactory("test-passphrase-12345".toByteArray()))
            .allowMainThreadQueries()
            .build()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun boxInsertQueryUpdateDelete() {
        val dao = database.boxDao()
        val id = dao.insertBox(Box(name = "Test Box", passwordHash = "somehash"))

        val boxes = dao.getAllBoxesSync()
        assertEquals(1, boxes.size)
        assertEquals("Test Box", boxes[0].name)
        assertEquals(id, boxes[0].id)

        dao.updateBox(Box(id = id, name = "Renamed Box", passwordHash = "somehash"))
        assertEquals("Renamed Box", dao.getAllBoxesSync()[0].name)

        dao.deleteBoxById(id)
        assertTrue(dao.getAllBoxesSync().isEmpty())
    }

    @Test
    fun autoGeneratedIdsAreDistinct() {
        val dao = database.boxDao()
        val id1 = dao.insertBox(Box(name = "A", passwordHash = "h1"))
        val id2 = dao.insertBox(Box(name = "B", passwordHash = "h2"))
        assertTrue(id1 != id2)
    }

    @Test
    fun messageCrudAndCascadeDelete() {
        val dao = database.boxDao()
        val boxId = dao.insertBox(Box(name = "Box", passwordHash = "h"))

        dao.insertMessage(Message(boxId = boxId, encryptedText = "cipher1", timestamp = 100))
        dao.insertMessage(Message(boxId = boxId, encryptedText = "cipher2", timestamp = 200))

        val messages = dao.getMessagesByBoxIdSync(boxId)
        assertEquals(2, messages.size)
        assertEquals(listOf("cipher1", "cipher2"), messages.map { it.encryptedText })

        val first = messages.first { it.encryptedText == "cipher1" }
        dao.updateMessage(first.copy(encryptedText = "cipher1-updated"))
        assertEquals(
            "cipher1-updated",
            dao.getMessagesByBoxIdSync(boxId).first { it.encryptedText == "cipher1-updated" }.encryptedText
        )

        dao.deleteMessagesBefore(boxId, 150)
        assertEquals(1, dao.getMessagesByBoxIdSync(boxId).size)
        assertEquals("cipher2", dao.getMessagesByBoxIdSync(boxId)[0].encryptedText)

        dao.deleteBoxById(boxId)
        assertTrue(dao.getMessagesByBoxIdSync(boxId).isEmpty())
    }
}
