-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.coroutines.**
-keep class kotlin.Metadata { *; }
-keep class net.sqlcipher.** { *; }
-keep class net.zetetic.** { *; }
-dontwarn com.google.errorprone.annotations.**
-dontwarn javax.annotation.**
